TXTwoPointCluster:
  binning_scale: Log
  max_sep: 250.0
  min_sep: 10.0
  nbins: 15
  redshift_bin_edges:
  - 0.2
  - 0.6
  - 1.0
  richness_bin_edges:
  - 20
  - 30
  - 300
  units: arcmin
global:
  chunk_rows: 100000
  nside: 64
  pixelization: healpix
  sparse: true
